apiVersion: v1
data:
  database-url: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfM0RieXFDdmpQbk43QGVwLW11dGUtaGlsbC1hZ3o1bnA4Ny1wb29sZXIuYy0yLmV1LWNlbnRyYWwtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU=
  jwt-secret: MWZhZmVhdGluZ2llcm5pc25maW5haWVzbmZpbmFpcm4=
kind: Secret
metadata:
  name: app-secrets
