apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "todo-stack.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.configMap.data.APP_NAME | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
