apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: default
  annotations:
    # Enable cert-manager to automatically provision SSL certificate
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Force HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  # Use nginx ingress controller (newer way)
  ingressClassName: nginx
  tls:
  - hosts:
    - testservers.online
    - www.testservers.online
    # This secret will be automatically created by cert-manager
    secretName: testservers-online-tls
  rules:
  - host: testservers.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: www.testservers.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
