{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "todo-chart.backendLabels" . | nindent 4 }}
  annotations:
    {{- include "todo-chart.aiOpsAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "todo-chart.selectorLabels" . | nindent 4 }}
    tier: backend
{{- end }}
