{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "todo-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "todo-chart.aiOpsAnnotations" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | default "" | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | default "" | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | default "" | quote }}
{{- end }}
